version: 0.2
phases:
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo "Executing Elastic Beanstalk Update"
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/store-pipline-project-0.0.1-SNAPSHOT.jar